# Importing Libraries
import time
import hashlib
from django.conf import settings


# Hash is generated by applying SHA-512 algorithm to the string (which is generated using fields in the request / response and a pipe(|) between fields)
def generate_hash(request):
    start_time = time.time()

    hash = hashlib.sha512(str(request).encode("utf-8")).hexdigest()

    response_time = time.time() - start_time
    settings.HASH_GENERATE_RESPONSE_TIME.observe(response_time)

    return hash
