# Importing Python Libraries
import os
from dotenv import load_dotenv
from django.conf import settings

# Importing Project Files
from .yoomoneyPaymentGateway import YooMoney

load_dotenv()

# Reading environment credentials
SHOP_ID = os.getenv("YOOMONEY_SHOP_ID")
SECRET_KEY = os.getenv("YOOMONEY_SECRET_KEY")
env = "test" if os.getenv("ENV") == "staging" else "prod"

yooMoney = YooMoney(id=SHOP_ID, secretKey=SECRET_KEY, env=env)

"""
initiateTransactionYooMoney - initiates the transaction via YooMoney.

Parameters of the function:
* data (type dictionary) - holds all the data posted by client, required for transaction to initiate
transactionDetails (required by YooMoney) is then generated.

Return values of the function:
* finalResult (type dictionary) - response generated by YooMoney (can be either success/failure depending on the payload generated)
"""


def initiateTransactionYooMoney(data):
    transactionDetails = {
        "amount": data["amount"],
        "purposeMessage": "Payment for {}".format(data["productInformation"]),
        "paymentMode": True if "paymentMode" in data else False,
        "redirectURL": data["redirectURL"],
    }

    # initiating the transaction.
    finalResult = yooMoney.initiatePaymentAPI(params=transactionDetails)

    return finalResult
